### ISSUE TITLE
'batch correction assessment' raises an error if no LinerityReference sample are present

### ISSUE THREAD

**Issue by jaketmp** [phenomecentre/nPYc-Toolbox#20]
nPYc.reports.generateReport(data,'batch correction assessment'):

```
879                         if sum(lrMask) == 0:
880                                 raise ValueError('No %s samples defined with an AssayRole of %s' % (sampleType, assayRole))
```

Seems a little restrictive.

**Comment by Gscorreia89** [comment]
This particular bit has been removed, which means in theory it should be fine...
However, the helper function used in this report (batchCorrectionTest) is still expecting the dilution series to filter which features are passing dilution. I have removed these bits (see https://github.com/phenomecentre/nPYc-Toolbox/commit/3e259e988a1f154cd9c13e74a223c81a7e99d16b), which means now no filtering by dilution series should be done before (hence will work without dilution series). Will close after properly testing.

**Comment by jaketmp** [comment]
Does this imply that features should be filtered on the LR before batch correction?

**Comment by Gscorreia89** [comment]
To make it work for datasets without linearity reference - this has to be removed or made optional. What I will do before closing is try to refactor it a bit to be like the other reports - copy the dataset, and do an updateMasks(). The updateMasks method should handle flexibly whether or not we have LinearityReferences I think (if not then it will haha).
