### ISSUE TITLE
ISATAB export hardcodes optional columns

### ISSUE THREAD

**Issue by jaketmp** [phenomecentre/nPYc-Toolbox#22]
These columns are optional in _sampleMetadata_ and should not be hard-coded in ISATAB export.

- 'Study'
- 'Status'
- 'Age'
- 'Gender'
- 'Sampling Date'
- 'Acquired Time'
- 'Assay data name'
- 'Instrument'
- 'Sample Batch'

**Comment by jaketmp** [comment]
Mandated columns are in the docstring: https://github.com/phenomecentre/nPYc-Toolbox/blob/1088cf894b81e655e339dd0e547bc0d0a303fd8f/nPYc/objects/_dataset.py#L62

**Comment by nsadawi** [comment]
Yup, leave it with me!
