### ISSUE TITLE
Bruker BI-QUANT ivDR version 2.0 .xml format

### ISSUE THREAD

**Issue by Gscorreia89** [phenomecentre/nPYc-Toolbox#44]
The Bruker ivDr BI-QUANT-PS input functions need to be re-factored for version 2.0

**Comment by jaketmp** [comment]
Please tell me v2 doesn't duplicate values just because they're duplicated in the pdf anymore...

**Comment by carolinesands** [comment]
Add a switch to export either raw concentrations or LOD filtered

**Comment by Gscorreia89** [comment]
This has been fixed in https://github.com/phenomecentre/nPYc-Toolbox/commit/3a04c4196edfdfd20ba00de50ccf0cf2f09f5f43 , already in develop.

There are some changes to default behaviour in this version:
1 - If the ivDr version is 1.0, the usual 0 censored values taken from the 'value' field are returned.
2 - In higher versions, the 'rawConc' value is returned always instead of 'value' (more decimal places), but it is censored (set to 0) if the value is below the sample specific LOD. 

Switching between raw or LOD filtered will be implemented in the ongoing refactor of targeted objects: https://github.com/phenomecentre/nPYc-Toolbox/tree/feature/abstractTargetedDataset

The unitests have been changed to address the changes. Since there is no longer a bug, I will close this issue, but will open a new one with enhancement to improve the unitests and test datasets - the v2 parsing is not being formally tested at the moment.
