### ISSUE TITLE
sklearn future warning

### ISSUE THREAD

**Issue by carolinesands** [phenomecentre/nPYc-Toolbox#47]
The sklearn.decomposition.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.decomposition. Anything that cannot be imported from sklearn.decomposition is now part of the private API.

**Comment by Gscorreia89** [comment]
This was an issue with pyChemometrics that has been fixed and not with nPYc-Toolbox. Should not happen with updated versions of both.
